mkdir media
touch media/remove_when_something_is_here
mkdir docs
touch docs/remove_when_something_is_here
mkdir data
touch data/remove_when_something_is_here
mkdir submodules
touch submodules/remove_when_something_is_here
mkdir sources
touch sources/remove_when_something_is_here
echo Folders and temporary placeholders created!